# Generated by Django 5.0.6 on 2026-04-11 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='female', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('التحرش الجسدي', 'التحرش الجسدي'), ('التحرش اللفظي', 'التحرش اللفظي'), ('التحرش الإلكتروني', 'التحرش الإلكتروني'), ('العنف اللفظي أو التهديد', 'العنف اللفظي أو التهديد'), ('الإقصاء الاجتماعي', 'الإقصاء الاجتماعي'), ('أخرى', 'أخرى')], max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('perpetrator', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('جديد', 'جديد'), ('قيد المعالجة', 'قيد المعالجة'), ('موعد محدد', 'موعد محدد'), ('تم الحل', 'تم الحل')], default='جديد', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.counselor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('solutions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='api.counselor')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_report', to='api.report')),
            ],
        ),
    ]
