# Generated by Django 5.0.6 on 2026-04-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_status_studentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='counselors/photos/'),
        ),
    ]
