# Generated by Django 5.0.6 on 2026-04-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_photo_to_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('التحرش الجسدي', 'التحرش الجسدي'), ('التحرش اللفظي', 'التحرش اللفظي'), ('التحرش الإلكتروني', 'التحرش الإلكتروني'), ('العنف اللفظي أو التهديد', 'العنف اللفظي أو التهديد'), ('الإقصاء الاجتماعي', 'الإقصاء الاجتماعي'), ('التمييز', 'التمييز'), ('التمييز العرقي', 'التمييز العرقي'), ('التمييز الجنسي', 'التمييز الجنسي'), ('التمييز الديني', 'التمييز الديني'), ('التحرش الجنسي', 'التحرش الجنسي'), ('أخرى', 'أخرى')], max_length=100),
        ),
    ]
