# Generated by Django 5.0.6 on 2026-04-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_discrimination_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='perpetrator_classe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
