# Generated by Django 5.0.6 on 2026-04-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activite_sitecontent_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='numero_dossier',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
