# Generated by Django 5.0.6 on 2026-04-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_numero_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='progress',
            field=models.CharField(choices=[('en_cours', 'En cours de suivi'), ('amelioration', 'Amélioration notable'), ('resolu', 'Résolu')], default='en_cours', max_length=20),
        ),
    ]
