# Generated by Django 5.0.6 on 2026-04-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_session_report_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('professeurs', 'Professeurs'), ('activites', 'Activités scolaires')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, choices=[('education_islamique', 'Éducation islamique'), ('histoire_geo', 'Histoire-Géographie'), ('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('francais', 'Français'), ('informatique', 'Informatique'), ('anglais', 'Anglais'), ('sport', 'Sport'), ('svt', 'SVT'), ('autre', 'Autre')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
