# Generated by Django 5.0.6 on 2026-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_photo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('professeurs', 'Professeurs'), ('activites', 'Activités scolaires'), ('accueil', 'Diaporama Accueil')], max_length=20),
        ),
    ]
